addon/urls.py
from django.conf.urls import *
from . import views
# class CsrfExemptResource( Resource ):
#     def __init__( self, handler, authentication = None ):
#         super( CsrfExemptResource, self ).__init__( handler, authentication )
#         self.csrf_exempt = getattr( self.handler, 'csrf_exempt', True )
urlpatterns = patterns(
    '',
    url(r'^update/$', views.Update, name='index'),
    url(r'^$', views.AddonListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.AddonDetailView.as_view(), name='detail')
)

addonapi/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# urlpatterns = patterns('',
#     # Examples:
#     # url(r'^$', 'addonapi.views.home', name='home'),
#     # url(r'^addonapi/', include('addonapi.foo.urls')),

#     # Uncomment the admin/doc line below to enable admin documentation:
#     # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

#     # Uncomment the next line to enable the admin:
#     # url(r'^admin/', include(admin.site.urls)),
# )
admin.autodiscover()

urlpatterns = patterns('',
    (r'^api/', include('api.urls', namespace="api")),
    (r'^addons/', include('addon.urls', namespace="addon")),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += patterns('',
	(r'^static/(.*)$', 'django.views.static.serve', {
		'document_root': settings.STATIC_ROOT
	}),
)

api/urls.py
from django.conf.urls.defaults import *
from piston.authentication import HttpBasicAuthentication
from piston.resource import Resource
from api.handlers import AddonHandler


class CsrfExemptResource(Resource):
    def __init__(self, handler, authentication=None):
        super(CsrfExemptResource, self).__init__(handler, authentication)
        self.csrf_exempt = getattr(self.handler, 'csrf_exempt', True)

auth = HttpBasicAuthentication(realm="Addon Api")
addon_resource = CsrfExemptResource(AddonHandler, authentication=auth)

urlpatterns = patterns(
    '',
    url(r'^$', addon_resource, {'emitter_format': 'json'}, name='all'),
    url(
        r'^(?P<addon_name>.*)/$',
        addon_resource,
        {'emitter_format': 'json'},
        name='single'
    )
)

addon/models.py
from django.db import models
from addon.fields import JSONField
from django.template.defaultfilters import slugify


class Addon(models.Model):
    name = models.CharField(max_length=30, unique=True)
    config_vars = JSONField(default='', blank=True, null=True)
    slug = models.SlugField(max_length=30, blank=True, default='')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ("addon:detail", (), {"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Addon, self).save(*args, **kwargs)

api/models.py
from django.db import models

# Create your models here.

addon/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView

from .models import Addon
from .update import updateAddons
import os
import json


# cred_file = open(os.environ["CRED_FILE"])
# data = json.load(cred_file)
# addons = Addon.objects.all()

# for addon in addons:
# 	name = addon.name
# 	if addon.config_vars != data[addon.name.upper()]:
# 		addon.config_vars = data[addon.name.upper()]
# 	addon.save()

def Update(request):
	updateAddons()
	return redirect('/addons/')


class AddonListView(ListView):
	model = Addon


class AddonDetailView(DetailView):
	model = Addon

api/views.py
# Create your views here.

addon/templates/addon/addon_detail.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}{{ addon.name }} | {% endblock %}

{% block page_content %}

<h2>{{ addon.name }}</h2>

{{ addon.config_vars|linebreaks }}
<p>{{ addon.date_modified }}</p>
<p><a href="{% url 'addon:list' %}" class="btn">&larr; Add-On list</a></p>
{% endblock %}

addon/templates/addon/addon_list.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}Addon List | {% endblock %}

{% block page_content %}

<h2>Addons</h2>

<ul>
	{% for addon in addon_list %}
	<li><a href="{% url 'addon:detail' addon.slug %}">{{ addon.name }}</a></li>
	{% empty %}
	<li>Sorry, no Add-On's yet. Check back soon!</li>
	{% endfor %}
</ul>

{% endblock %}

addon/templates/addon_list.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_title %}Addon List | {% endblock %}

{% block page_content %}

<h2>Addons</h2>

<ul>
	{% for addon in addon_list %}
	<li><a href="{% addon.get_absolute_url %}">{{ addon.name }}</a></li>
	{% empty %}
	<li>Sorry, no addon's yet. Check back soon!</li>
	{% endfor %}
</ul>

{% endblock %}

addonapi/templates/_layouts/base.html
<!doctype html>
<html>
	<head>
		<title>{% block page_title %}{% endblock %}AddonApi</title>
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css">
	</head>
	<body>
		<div class="container">
			<h1>Addon-API</h1>
			{% block page_content %}{% endblock %}
		</div>
	</body>
</html>

addonapi/templates/index.html
{% extends "_layouts/base.html" %}
{% load url from future %}

{% block page_content %}
<div class="row-fluid">
	<a href="{% url 'addon:list' %}" class="btn">View Addons</a>
</div>
{% endblock %}